# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityToCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('city_name_from', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name_to', models.CharField(blank=True, max_length=255, null=True)),
                ('mps', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='terrain',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='type_city',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
